POST http://localhost:5000/upload HTTP/1.1
content-type: application/json

{
    "image": "pic.png",
    "title": "mayank234",
    "tags": ["profile", "person"]
}

###
GET http://localhost:5000/ HTTP/1.1
content-type: application/json

###
POST http://localhost:5000/images/ HTTP/1.1
content-type: application/json  

###
POST http://localhost:5000/user/signup HTTP/1.1
content-type: application/json  

{
    "password": "test",
    "email": "testing",
    "name": "mayank"
}

###

# @name login
POST http://localhost:5000/user/login HTTP/1.1
content-type: application/json  

{
    "password": "test",
    "email": "testing"
}

###
GET http://localhost:5000/profile?secret_token={{login.response.body.token}} HTTP/1.1
content-type: application/json  

###
# @name upload
POST http://localhost:5000/upload?secret_token={{login.response.body.token}} HTTP/1.1
content-type: application/json  

{
    "image": "pic.png",
    "title": "mayank234",
    "tags": ["profile", "person"]
}

###
DELETE http://localhost:5000/delete/{{upload.response.body.res.id}}?secret_token={{login.response.body.token}} HTTP/1.1
content-type: application/json  